FROM ubuntu:latest

RUN apt update -qq && apt install -y python-software-properties
RUN apt update -qq && apt install -y mosquitto-clients

RUN mkdir /ca

ENTRYPOINT [ "mosquitto_pub", "-h", "mosquitto", "-p", "8883", "--cafile", "/ca/ca.crt.pem", "--cert", "/ca/mqtt-client.local.crt.pem", "--key", "/ca/mqtt-client.local.key.pem" ]
CMD [ "-t", "test", "-m", "Hello World" ]
