FROM ubuntu:latest

RUN apt update -qq && apt install -y python-software-properties
RUN apt update -qq && apt install -y mosquitto-clients

ENTRYPOINT [ "mosquitto_pub", "-h", "mosquitto" ]
CMD [ "-t", "test", "-m", "Hello World" ]
