FROM ubuntu:latest

COPY /bin/tini /tini
RUN chmod +x /tini

RUN apt update -qq && apt install -y python-software-properties
RUN apt update -qq && apt install -y mosquitto-clients

RUN mkdir /ca

ENTRYPOINT [ "/tini", "--", "mosquitto_sub", "-h", "mqtt.local", "-p", "8883", "--cafile", "/ca/ca.crt.pem", "--cert", "/ca/mqtt-client.local.crt.pem", "--key", "/ca/mqtt-client.local.key.pem" ]
CMD [ "-t", "test" ]
